"use client";

import { useState } from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { RewardContext } from "./app_context";

const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [reward, setReward] = useState(0);
  return (
    <html lang="en">
      <body className={inter.className}>
        <RewardContext.Provider value={{ reward, setReward }}>
          {children}
        </RewardContext.Provider>
      </body>
    </html>
  );
}
